"""Exit-Policy Walk-Forward Harness — same-entry comparison framework.

Architectural principle: exit logic is SCANNER-SPECIFIC, not global. Output
is structured to enforce that — every verdict row keys on (scanner, symbol).

Guardrails (architect-mandated 2026-05-03):
  1. SAME-ENTRY comparison only. Each runner generates ONE signal set, then
     each policy in policies[] is evaluated against IDENTICAL entries / fees /
     slippage. No cross-policy signal-set drift permitted.
  2. Every result row includes EV LIFT vs baseline (the named baseline policy).
  3. n_oos < 20 → verdict=PARKED (not PASS). Combats the tiny-n false-hope
     pattern observed in entry-pattern W/F (positive Q4 / negative IS).
  4. Output is a flat (scanner, symbol, exit_policy, …) table — no global
     "winning exit" claim ever — only per-scanner-per-symbol verdicts.
  5. EV-realization metrics:
       mfe_capture = realized_pct_profit / max_favorable_excursion_pct
                     (averaged over WINNING trades only; range [0,1])
       mae_escape  = 1 − (realized_loss_pct / max_adverse_excursion_pct)
                     (averaged over LOSING trades only; 1.0=perfect escape)
     These tell you WHY a policy beats baseline:
       higher mfe_capture → better profit harvesting
       higher mae_escape  → better loss cutting

Quarter boundaries match wf_harness:
  Q1 2025-10-01 → 2025-12-01  IS (partial — cache starts 2025-11-05)
  Q2 2025-12-01 → 2026-02-01  IS
  Q3 2026-02-01 → 2026-03-01  OOS
  Q4 2026-03-01 → 2026-05-01  OOS

Verdict rules per (scanner × symbol × policy) cell, scored against the named
baseline cell:
  PARKED          — n_oos < 20  (insufficient OOS sample)
  KILL            — ev_lift_oos <= 0  (policy worse than or equal to baseline OOS)
  HOLD            — 0 < ev_lift_oos <= $0.10  (positive but below ship floor)
  PASS            — ev_lift_oos > $0.10  AND  ev_lift_q3 >= 0  AND  ev_lift_q4 >= 0
                    (lift must be positive on BOTH OOS halves to avoid Q4-quirks)

The baseline policy itself gets verdict=BASELINE (no lift to compare).
"""
from __future__ import annotations

import json
import math
import statistics
import time as _time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

ROOT = Path("/home/opc/crypto-trading-bot")
CACHE_DIR = ROOT / "storage" / "candle_cache"

QUARTERS: Dict[str, Tuple[str, str]] = {
    "Q1": ("2025-10-01", "2025-12-01"),
    "Q2": ("2025-12-01", "2026-02-01"),
    "Q3": ("2026-02-01", "2026-03-01"),
    "Q4": ("2026-03-01", "2026-05-01"),
}
IS_QUARTERS = ("Q1", "Q2")
OOS_QUARTERS = ("Q3", "Q4")

# Fee math — single variant default (C_maker_scalper) since baseline is fixed
FEE_MAKER_PCT = 0.000236     # 0.02% × 1.18 GST
FEE_TAKER_PCT = 0.00059      # 0.05% × 1.18 GST
SCALPER_WINDOW_BTC_ETH_SEC = 1800
SCALPER_WINDOW_OTHER_SEC = 900

# Verdict gates
N_OOS_PARK = 20            # n_oos < 20 → PARKED
EV_LIFT_HOLD_FLOOR = 0.0   # >0 = HOLD
EV_LIFT_PASS_FLOOR = 0.10  # >$0.10 + sign-ok-on-both-OOS-halves = PASS

NOTIONAL_DEFAULT = 1000.0


# ──────────────────────────────────────────────────────────────────────
# Data structures
# ──────────────────────────────────────────────────────────────────────
@dataclass
class Signal:
    """A single entry decision — generated by a scanner detector once,
    then evaluated against multiple exit policies."""
    symbol: str
    entry_idx: int
    entry_ts: pd.Timestamp
    side: str                       # 'long' | 'short'
    entry_price: float
    sweep_extreme: float            # for SL anchoring (low for LONG sweep, high for SHORT)
    atr_at_entry: float
    extra: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExitOutcome:
    exit_idx: int
    exit_ts: pd.Timestamp
    exit_price: float
    exit_reason: str
    holding_bars: int
    holding_sec: int
    mfe_pct: float                  # max favorable excursion over the eval window
    mae_pct: float                  # max adverse excursion over the eval window
    realized_pct: float             # signed: + for profit, - for loss


@dataclass
class TradeResult:
    """Combined per-(signal × policy) record."""
    scanner: str
    symbol: str
    policy: str
    entry_ts: pd.Timestamp
    side: str
    entry_price: float
    exit_price: float
    exit_reason: str
    holding_sec: int
    holding_bars: int
    notional_usd: float
    gross_pct: float                # = realized_pct
    gross_usd: float
    fee_usd: float
    net_usd: float
    mfe_pct: float
    mae_pct: float
    extra: Dict[str, Any] = field(default_factory=dict)


class ExitPolicy(ABC):
    """Pluggable exit policy. Same-entry guarantee: every policy receives
    identical Signal + identical df slice; only their evaluate() differs."""
    name: str = "abstract"
    is_baseline: bool = False        # exactly ONE policy per runner is baseline

    @abstractmethod
    def evaluate(
        self,
        df: pd.DataFrame,
        sig: Signal,
        tf_min: int,
        eval_window_bars: int,
    ) -> ExitOutcome:
        """Must be deterministic — same inputs → same outputs. No randomness."""
        ...


# ──────────────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────────────
def quarter_of(ts: pd.Timestamp) -> Optional[str]:
    if ts.tzinfo is None:
        ts = ts.tz_localize("UTC")
    for q, (s, e) in QUARTERS.items():
        if pd.Timestamp(s, tz="UTC") <= ts < pd.Timestamp(e, tz="UTC"):
            return q
    return None


def load_candles(symbol: str, tf: str) -> pd.DataFrame:
    p = CACHE_DIR / f"{symbol}_USDT_{tf}.parquet"
    if not p.exists():
        raise FileNotFoundError(f"missing cache: {p}")
    df = pd.read_parquet(p)
    if df.index.tz is None:
        df.index = df.index.tz_localize("UTC")
    return df.sort_index()


def add_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
    h = df["high"].astype(float); l = df["low"].astype(float)
    c = df["close"].astype(float).shift(1)
    tr = pd.concat([(h - l).abs(), (h - c).abs(), (l - c).abs()], axis=1).max(axis=1)
    return tr.rolling(period, min_periods=period).mean()


def compute_mfe_mae(
    df: pd.DataFrame,
    entry_idx: int,
    side: str,
    entry_price: float,
    eval_window_bars: int,
) -> Tuple[float, float]:
    """MFE/MAE in pct over a fixed look-forward window (policy-AGNOSTIC).
    The window is the same across all policies so MFE/MAE is a property of
    the SIGNAL, not the policy."""
    end_idx = min(entry_idx + eval_window_bars, len(df) - 1)
    if end_idx <= entry_idx:
        return 0.0, 0.0
    highs = df["high"].astype(float).values[entry_idx + 1: end_idx + 1]
    lows = df["low"].astype(float).values[entry_idx + 1: end_idx + 1]
    if side == "long":
        max_fav_price = float(np.max(highs)) if len(highs) else entry_price
        max_adv_price = float(np.min(lows)) if len(lows) else entry_price
        mfe = (max_fav_price - entry_price) / entry_price
        mae = (max_adv_price - entry_price) / entry_price   # negative
    else:
        max_fav_price = float(np.min(lows)) if len(lows) else entry_price
        max_adv_price = float(np.max(highs)) if len(highs) else entry_price
        mfe = (entry_price - max_fav_price) / entry_price
        mae = (entry_price - max_adv_price) / entry_price   # negative
    return float(mfe), float(mae)


def fee_for_trade(symbol: str, notional: float, holding_sec: int) -> float:
    """Variant C: maker entry + scalper-eligible exit (per Patch 5.18 fee model)."""
    entry_fee = notional * FEE_MAKER_PCT
    window = SCALPER_WINDOW_BTC_ETH_SEC if symbol in ("BTC", "ETH") else SCALPER_WINDOW_OTHER_SEC
    exit_fee = 0.0 if holding_sec <= window else notional * FEE_TAKER_PCT
    return entry_fee + exit_fee


# ──────────────────────────────────────────────────────────────────────
# Aggregation
# ──────────────────────────────────────────────────────────────────────
# Cell stats are returned as plain dicts (see aggregate_cell()) — no dataclass
# (Python identifiers can't contain '$', and dicts give us the cleanest schema.)


def _cumulative_drawdown(nets_in_order: List[float]) -> float:
    """Max drawdown in $ from running equity curve."""
    peak = 0.0
    eq = 0.0
    max_dd = 0.0
    for n in nets_in_order:
        eq += n
        peak = max(peak, eq)
        dd = peak - eq
        max_dd = max(max_dd, dd)
    return max_dd


def aggregate_cell(trades: List[TradeResult]) -> Dict[str, Any]:
    """Per-cell aggregate. trades must be sorted by entry_ts for max_dd."""
    if not trades:
        return {
            "n": 0, "n_is": 0, "n_oos": 0, "n_q1": 0, "n_q2": 0, "n_q3": 0, "n_q4": 0,
            "ev_is_$": 0.0, "ev_oos_$": 0.0, "ev_q3_$": 0.0, "ev_q4_$": 0.0, "ev_all_$": 0.0,
            "wr_is": 0.0, "wr_oos": 0.0,
            "avg_hold_sec_is": 0.0, "avg_hold_sec_oos": 0.0,
            "max_dd_is_$": 0.0, "max_dd_oos_$": 0.0,
            "mfe_capture_oos": 0.0, "mae_escape_oos": 0.0,
        }
    by_q: Dict[str, List[TradeResult]] = {q: [] for q in QUARTERS}
    for t in trades:
        q = quarter_of(t.entry_ts)
        if q is not None:
            by_q[q].append(t)
    is_trades = by_q["Q1"] + by_q["Q2"]
    oos_trades = by_q["Q3"] + by_q["Q4"]

    def _agg(buf: List[TradeResult]) -> Dict[str, float]:
        if not buf:
            return {"n": 0, "ev_$": 0.0, "wr": 0.0, "avg_hold_sec": 0.0,
                    "max_dd_$": 0.0, "mfe_capture": 0.0, "mae_escape": 0.0}
        nets = [t.net_usd for t in buf]
        ev = float(np.mean(nets))
        wins = [t for t in buf if t.net_usd > 0]
        losses = [t for t in buf if t.net_usd <= 0]
        wr = len(wins) / len(buf)
        avg_hold = float(np.mean([t.holding_sec for t in buf]))
        # Order-stable cumulative drawdown
        nets_sorted = [t.net_usd for t in sorted(buf, key=lambda x: x.entry_ts)]
        max_dd = _cumulative_drawdown(nets_sorted)
        # MFE capture (only meaningful for winners)
        caps = []
        for t in wins:
            if t.mfe_pct > 1e-9:
                # realized_pct on winner is positive; clamp to [0, 1]
                cap = max(0.0, min(1.0, t.gross_pct / t.mfe_pct))
                caps.append(cap)
        mfe_cap = float(np.mean(caps)) if caps else 0.0
        # MAE escape (only meaningful for losers)
        escs = []
        for t in losses:
            mae_abs = abs(t.mae_pct)
            if mae_abs > 1e-9:
                lost_abs = abs(t.gross_pct)
                esc = max(0.0, min(1.0, 1.0 - lost_abs / mae_abs))
                escs.append(esc)
        mae_esc = float(np.mean(escs)) if escs else 0.0
        return {
            "n": len(buf), "ev_$": ev, "wr": wr,
            "avg_hold_sec": avg_hold, "max_dd_$": max_dd,
            "mfe_capture": mfe_cap, "mae_escape": mae_esc,
        }

    is_s = _agg(is_trades)
    oos_s = _agg(oos_trades)
    q3_s = _agg(by_q["Q3"])
    q4_s = _agg(by_q["Q4"])
    all_s = _agg(trades)

    return {
        "n": len(trades),
        "n_q1": len(by_q["Q1"]), "n_q2": len(by_q["Q2"]),
        "n_q3": len(by_q["Q3"]), "n_q4": len(by_q["Q4"]),
        "n_is": is_s["n"], "n_oos": oos_s["n"],
        "ev_is_$": is_s["ev_$"], "ev_oos_$": oos_s["ev_$"],
        "ev_q3_$": q3_s["ev_$"], "ev_q4_$": q4_s["ev_$"], "ev_all_$": all_s["ev_$"],
        "wr_is": is_s["wr"], "wr_oos": oos_s["wr"],
        "avg_hold_sec_is": is_s["avg_hold_sec"], "avg_hold_sec_oos": oos_s["avg_hold_sec"],
        "max_dd_is_$": is_s["max_dd_$"], "max_dd_oos_$": oos_s["max_dd_$"],
        "mfe_capture_oos": oos_s["mfe_capture"], "mae_escape_oos": oos_s["mae_escape"],
    }


# ──────────────────────────────────────────────────────────────────────
# Verdict — vs baseline
# ──────────────────────────────────────────────────────────────────────
def verdict_vs_baseline(
    cell: Dict[str, Any],
    baseline: Dict[str, Any],
    is_baseline: bool,
) -> Dict[str, Any]:
    if is_baseline:
        return {
            "verdict": "BASELINE",
            "ev_lift_oos_$": 0.0, "ev_lift_is_$": 0.0,
            "ev_lift_q3_$": 0.0, "ev_lift_q4_$": 0.0,
            "wr_delta_oos": 0.0,
            "avg_hold_delta_sec_oos": 0.0,
            "max_dd_delta_oos_$": 0.0,
        }
    if cell["n_oos"] < N_OOS_PARK:
        v = "PARKED"
    else:
        ev_lift_oos = cell["ev_oos_$"] - baseline["ev_oos_$"]
        ev_lift_q3 = cell["ev_q3_$"] - baseline["ev_q3_$"]
        ev_lift_q4 = cell["ev_q4_$"] - baseline["ev_q4_$"]
        if ev_lift_oos > EV_LIFT_PASS_FLOOR and ev_lift_q3 >= 0 and ev_lift_q4 >= 0:
            v = "PASS"
        elif ev_lift_oos > EV_LIFT_HOLD_FLOOR:
            v = "HOLD"
        else:
            v = "KILL"
    return {
        "verdict": v,
        "ev_lift_oos_$": cell["ev_oos_$"] - baseline["ev_oos_$"],
        "ev_lift_is_$":  cell["ev_is_$"]  - baseline["ev_is_$"],
        "ev_lift_q3_$":  cell["ev_q3_$"]  - baseline["ev_q3_$"],
        "ev_lift_q4_$":  cell["ev_q4_$"]  - baseline["ev_q4_$"],
        "wr_delta_oos":  cell["wr_oos"]   - baseline["wr_oos"],
        "avg_hold_delta_sec_oos": cell["avg_hold_sec_oos"] - baseline["avg_hold_sec_oos"],
        "max_dd_delta_oos_$":     cell["max_dd_oos_$"]    - baseline["max_dd_oos_$"],
    }


# ──────────────────────────────────────────────────────────────────────
# Runner
# ──────────────────────────────────────────────────────────────────────
def evaluate_signal_through_policies(
    df: pd.DataFrame,
    sig: Signal,
    policies: List[ExitPolicy],
    scanner: str,
    tf_min: int,
    eval_window_bars: int,
    notional: float = NOTIONAL_DEFAULT,
) -> List[TradeResult]:
    """Run ONE signal through ALL policies. Same entry, same eval window,
    same fees — only exit logic varies. Returns one TradeResult per policy."""
    out: List[TradeResult] = []
    # Compute MFE/MAE ONCE per signal — it's policy-agnostic (signal property)
    mfe, mae = compute_mfe_mae(df, sig.entry_idx, sig.side, sig.entry_price, eval_window_bars)
    for p in policies:
        try:
            outc = p.evaluate(df, sig, tf_min, eval_window_bars)
        except Exception as e:
            # Skip this policy for this signal — don't taint the cell
            continue
        gross_pct = outc.realized_pct
        gross_usd = gross_pct * notional
        fee = fee_for_trade(sig.symbol, notional, outc.holding_sec)
        net = gross_usd - fee
        # Use signal-level mfe/mae (not the policy's window — same across policies)
        out.append(TradeResult(
            scanner=scanner, symbol=sig.symbol, policy=p.name,
            entry_ts=sig.entry_ts, side=sig.side,
            entry_price=sig.entry_price, exit_price=outc.exit_price,
            exit_reason=outc.exit_reason,
            holding_sec=outc.holding_sec, holding_bars=outc.holding_bars,
            notional_usd=notional, gross_pct=gross_pct, gross_usd=gross_usd,
            fee_usd=fee, net_usd=net, mfe_pct=mfe, mae_pct=mae,
            extra=dict(sig.extra),
        ))
    return out


def run_exit_wf(
    *,
    scanner: str,
    symbols: List[str],
    tf: str,
    tf_min: int,
    signal_generator: Callable[[pd.DataFrame, str], List[Signal]],
    policies: List[ExitPolicy],
    out_dir: Path,
    eval_window_bars: int = 60,    # 60 × 5m = 5 hours; covers any policy max_hold
    notional: float = NOTIONAL_DEFAULT,
    extra_notes: Optional[List[str]] = None,
) -> Dict[str, Any]:
    """Main runner. Generates signals once per symbol, evaluates all policies."""
    out_dir.mkdir(parents=True, exist_ok=True)
    assert sum(1 for p in policies if p.is_baseline) == 1, \
        "exactly one policy must be marked is_baseline=True"
    baseline_name = next(p.name for p in policies if p.is_baseline)

    t0 = _time.time()
    cells: Dict[Tuple[str, str], Dict[str, Any]] = {}    # (symbol, policy) → cell stats
    all_trades: List[TradeResult] = []
    n_signals_per_sym: Dict[str, int] = {}

    for sym in symbols:
        try:
            df = load_candles(sym, tf)
        except FileNotFoundError as e:
            print(f"[{scanner}|{sym}] SKIP — {e}")
            continue
        df.attrs["symbol"] = sym
        sigs = signal_generator(df, sym)
        n_signals_per_sym[sym] = len(sigs)
        print(f"[{scanner}|{sym}] {len(sigs)} signals generated")

        # Group trades by policy for this symbol
        trades_by_policy: Dict[str, List[TradeResult]] = {p.name: [] for p in policies}
        for s in sigs:
            policy_trades = evaluate_signal_through_policies(
                df, s, policies, scanner, tf_min, eval_window_bars, notional,
            )
            for tr in policy_trades:
                trades_by_policy[tr.policy].append(tr)
                all_trades.append(tr)
        for pname, trs in trades_by_policy.items():
            cells[(sym, pname)] = aggregate_cell(trs)

    # Build output rows: (scanner × symbol × policy) with verdict-vs-baseline
    rows: List[Dict[str, Any]] = []
    for sym in symbols:
        if (sym, baseline_name) not in cells:
            continue
        baseline_stats = cells[(sym, baseline_name)]
        for p in policies:
            cs = cells.get((sym, p.name))
            if cs is None:
                continue
            v = verdict_vs_baseline(cs, baseline_stats, p.is_baseline)
            row = {
                "scanner": scanner, "symbol": sym, "policy": p.name,
                "is_baseline": p.is_baseline,
                **cs, **v,
            }
            rows.append(row)

    wall = round(_time.time() - t0, 1)
    summary = {
        "scanner": scanner,
        "symbols": symbols,
        "tf": tf,
        "policies": [p.name for p in policies],
        "baseline_policy": baseline_name,
        "eval_window_bars": eval_window_bars,
        "notional": notional,
        "n_signals_per_sym": n_signals_per_sym,
        "n_trade_records": len(all_trades),
        "wall_sec": wall,
        "started_at": datetime.now(timezone.utc).isoformat(),
        "rows": rows,
    }

    (out_dir / "exit_walkforward.json").write_text(
        json.dumps(summary, indent=2, default=str)
    )

    # Markdown report
    md = [
        f"# {scanner} — Exit-Policy Walk-Forward Report",
        "",
        f"Generated: {summary['started_at']}",
        f"Wall: {wall}s   Symbols: {', '.join(symbols)}   TF: {tf}   "
        f"Eval window: {eval_window_bars} bars",
        f"Baseline policy: **{baseline_name}**",
        f"n trade records: {len(all_trades)}    "
        f"signals/sym: " + ", ".join(f"{k}={v}" for k, v in n_signals_per_sym.items()),
        "",
        "## Architect-mandated guardrails",
        "- Same entries / same fees / same slippage across all policies (only exit differs)",
        "- n_oos < 20 → **PARKED** (not PASS)",
        "- PASS requires ev_lift_oos > $0.10 AND ev_lift_q3 ≥ 0 AND ev_lift_q4 ≥ 0",
        "- Output is per (scanner × symbol × policy) — never a global winner",
        "",
    ]
    if extra_notes:
        md += ["## Notes", *extra_notes, ""]

    md += ["## Per-(scanner × symbol × policy) verdicts",
           "",
           "| scanner | symbol | policy | n_is | n_oos | base_ev | pol_ev | EV lift | wr Δ | hold_Δ_min | max_dd_Δ | mfe_cap | mae_esc | verdict |",
           "|---|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in rows:
        hold_delta_min = r["avg_hold_delta_sec_oos"] / 60.0
        # find baseline EV for that (scanner,symbol)
        bsl = next((rr for rr in rows if rr["symbol"] == r["symbol"] and rr["is_baseline"]), None)
        base_ev = bsl["ev_oos_$"] if bsl else 0.0
        md.append(
            f"| {r['scanner']} | {r['symbol']} | {r['policy']} | "
            f"{r['n_is']} | {r['n_oos']} | "
            f"${base_ev:+.3f} | ${r['ev_oos_$']:+.3f} | "
            f"${r['ev_lift_oos_$']:+.3f} | {r['wr_delta_oos']*100:+.1f}pp | "
            f"{hold_delta_min:+.1f} | ${r['max_dd_delta_oos_$']:+.2f} | "
            f"{r['mfe_capture_oos']*100:.0f}% | {r['mae_escape_oos']*100:.0f}% | "
            f"**{r['verdict']}** |"
        )

    # Per-symbol "winning policy" highlight (NOT a global winner — per symbol only)
    md += ["", "## Per-symbol winner (only among PASS / HOLD; PARKED skipped)", ""]
    for sym in symbols:
        sym_rows = [r for r in rows if r["symbol"] == sym and not r["is_baseline"]
                    and r["verdict"] in ("PASS", "HOLD")]
        if not sym_rows:
            md.append(f"- **{sym}**: no policy beats baseline (or all PARKED)")
            continue
        best = max(sym_rows, key=lambda r: r["ev_lift_oos_$"])
        md.append(
            f"- **{sym}**: `{best['policy']}` (verdict {best['verdict']}, "
            f"EV lift OOS = ${best['ev_lift_oos_$']:+.3f}/trade, n_oos={best['n_oos']})"
        )

    md += ["", "## Verdict count", "", "| Verdict | Count |", "|---|---|"]
    vc: Dict[str, int] = {}
    for r in rows:
        vc[r["verdict"]] = vc.get(r["verdict"], 0) + 1
    for v, n in sorted(vc.items(), key=lambda x: -x[1]):
        md.append(f"| {v} | {n} |")

    (out_dir / "report.md").write_text("\n".join(md) + "\n")
    print(f"=== {scanner} DONE ({wall}s)  rows={len(rows)} ===")
    return summary
