#!/usr/bin/env python3
"""ML Live-Calibration Daily Check — PATCH_G_5_22 (2026-05-02).

Hits /api/ml/live-calibration on VM4 and writes a verdict report.
Surfaces calibration drift per (scanner × family) so the architect knows
when it's safe to ship Phase F (ML-as-gate).

Verdict bands per bucket:
  🟢 OK         — calibration_error < 0.10
  🟡 WEAK       — 0.10 ≤ err < 0.30
  🔴 DRIFTING   — err ≥ 0.30
  ⚫ NO_DATA    — n < 5

Cron: 0 8 * * * (daily 08:00 UTC = 13:30 IST)
"""
from __future__ import annotations
import os
import json
import sys
import datetime as dt
from pathlib import Path
import urllib.request

ML_URL = os.environ.get("ML_DASHBOARD_URL", "http://10.0.2.4:8081")
ML_KEY = os.environ.get("ML_DASHBOARD_API_KEY", "")  # GET doesn't need it but harmless
OUT_DIR = Path("/home/opc/crypto-trading-bot/storage/verdicts")


def _fetch(path: str, timeout: int = 10):
    req = urllib.request.Request(f"{ML_URL}{path}")
    if ML_KEY:
        req.add_header("X-API-Key", ML_KEY)
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _band(err: float, n: int) -> str:
    if n < 5:
        return "⚫ NO_DATA"
    if err < 0.10:
        return "🟢 OK"
    if err < 0.30:
        return "🟡 WEAK"
    return "🔴 DRIFTING"


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    today = dt.datetime.now(dt.timezone.utc).date().isoformat()
    out_path = OUT_DIR / f"ml_calibration_{today}.md"

    try:
        cal = _fetch("/api/ml/live-calibration")
    except Exception as e:
        out_path.write_text(f"# ML Calibration {today}\n\n🔴 ERROR: failed to fetch — {e}\n")
        print(f"FAILED: {e}", file=sys.stderr)
        return 2

    buckets = cal.get("buckets", [])
    overall = cal.get("overall", {})

    # BRIER_SCORE_ADDITION — overall Brier from API + per-bucket recompute below
    overall_brier = (float(overall.get('avg_ml_probability', 0) or 0)
                     - float(overall.get('realized_mfe_wr', 0) or 0)) ** 2
    lines = [
        f"# ML Live-Calibration — {today}",
        f"_Generated by ml_calibration_check.py — runs daily 08:00 UTC._",
        "",
        "## Overall (last 200 trades)",
        f"- n: **{overall.get('n', 0)}**",
        f"- avg_ml_probability: **{overall.get('avg_ml_probability', 0):.3f}**",
        f"- realized_mfe_wr: **{overall.get('realized_mfe_wr', 0):.3f}**",
        f"- calibration_error: **{overall.get('calibration_error', 0):.3f}**",
        f"- **brier_score: {overall_brier:.4f}** (lower=better; 0=perfect, 0.25=worst-case binary)",
        "",
        "## Per-bucket verdict",
        "",
        "| Scanner | Family | n | avg_ml | realized_wr | err | brier | verdict |",
        "|---|---|---:|---:|---:|---:|---:|---|",
    ]

    drifting = []
    weak = []
    # BRIER_SCORE_ADDITION (2026-05-03) — track weighted Brier across all buckets
    brier_weighted_sum = 0.0
    brier_weight_n = 0
    for b in buckets:
        scn = b.get("scanner", "?")
        fam = b.get("family", "?")
        n = int(b.get("n", 0))
        ml = float(b.get("avg_ml_probability", 0) or 0)
        wr = float(b.get("realized_mfe_wr", 0) or 0)
        err = float(b.get("calibration_error", 0) or 0)
        # BRIER_SCORE_ADDITION — Brier per bucket = (avg_p - realized_wr)^2, weighted by n
        brier = (ml - wr) ** 2
        if n > 0:
            brier_weighted_sum += brier * n
            brier_weight_n += n
        band = _band(err, n)
        lines.append(f"| {scn} | {fam} | {n} | {ml:.3f} | {wr:.3f} | {err:.3f} | {brier:.4f} | {band} |")
        if "DRIFTING" in band:
            drifting.append(f"{scn}×{fam} (err={err:.2f}, n={n})")
        elif "WEAK" in band:
            weak.append(f"{scn}×{fam} (err={err:.2f}, n={n})")

    # BRIER_SCORE_ADDITION — weighted overall Brier across buckets + interpretation
    if brier_weight_n > 0:
        weighted_brier = brier_weighted_sum / brier_weight_n
        lines.append("")
        lines.append("## Brier Score (n-weighted across buckets)")
        lines.append(f"- **weighted_brier: {weighted_brier:.4f}**")
        if weighted_brier < 0.04:
            lines.append("  - 🟢 EXCELLENT calibration (< 0.04)")
        elif weighted_brier < 0.10:
            lines.append("  - 🟡 ACCEPTABLE (0.04-0.10) — usable for ranking, not for absolute thresholds")
        elif weighted_brier < 0.20:
            lines.append("  - 🟠 POOR — model probabilities not reliable as absolute estimates")
        else:
            lines.append("  - 🔴 BROKEN — model is uncalibrated; do NOT use ML probability as gate threshold")

    # Headline verdict
    lines.append("")
    lines.append("## Headline verdict")
    if drifting:
        lines.append(f"🔴 **DRIFTING cohorts ({len(drifting)})**: {', '.join(drifting)}")
        lines.append("→ **Phase F (ML-as-gate) NOT SAFE** until these stabilize. Lower thresholds will admit garbage.")
    elif weak:
        lines.append(f"🟡 **WEAK cohorts ({len(weak)})**: {', '.join(weak)}")
        lines.append("→ Phase F (ML-as-gate) DEFERRED. Watch for trend over next 3-7 days before reconsidering.")
    else:
        lines.append("🟢 **All cohorts well-calibrated.**")
        lines.append("→ Phase F (ML-as-gate) is safe to ship. Run definitive A/B as planned in PHASE_ROADMAP.")

    out_path.write_text("\n".join(lines) + "\n")
    print(f"OK — wrote {out_path}")
    print(f"  Drifting: {len(drifting)}, Weak: {len(weak)}, Healthy: {len(buckets) - len(drifting) - len(weak)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
